---
title: "Your Title"
subtitle: "BMIN503/EPID600 Final Project"
author: "FirstName LastName"
format: html
editor: visual
number-sections: true
embed-resources: true
---

------------------------------------------------------------------------

Use this template to complete your project throughout the course. Your Final Project presentation will be based on the contents of this document. Replace the title/name above and text below with your own, but keep the headers. Feel free to change the theme and other display settings, although this is not required. I added a new sentence

## Overview {#sec-overview}

This project aims to simplify finding good gene therapy candidates based on certain parameters. While focusing on AAV based gene therapy, the code will also be usable for other existing and future vectors such as lentivirus and liquid nanoparticle (LNP).

## Introduction {#sec-introduction}

Genetic diseases are health problems caused by defects in an individuals DNA. Because of this, most medicines and treatments only offer short term relief as the core issue with the DNA remains. In recent history, the rise of gene therapy has given hope to those with genetic diseases in the form of a long lasting cure by providing functional DNA via different vectors. The drawbacks of gene therapy include both the limitations of vectors as well as the long development time of treatments. Because of this, selecting what disease to develop drugs for is a critical step to save time and resources. This code works to provide an important resource to navigate through the thousand of genetic diseases in order to increase efficiency in diseases we can cure.

Being in the field of medicine, gene therapy is an interdisciplinary field. Ranging from doctors identifying diseases, geneticists sequencing genes, molecular biologists creating vectors, veterinarians overseeing animal trials, data scientists creating databases, and the many government agencies that oversee this, there are multiple fields that can contribute to working on this issue. Important data for this issue includes disease tropism, disease prevalence, and gene size, which can be found in various databases kept by different agencies.

## Methods {#sec-methods}

Describe the data used and general methodological approach used to address the problem described in the @sec-introduction. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.

## Results {#sec-results}

Describe your results and include relevant tables, plots, and code/comments used to obtain them. You may refer to the @sec-methods as needed. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

## Conclusion

This the conclusion. The @sec-results can be invoked here.
